image: k33g/free-wasm:0.0.3

tasks:
  - name: initialize
    before: |

      # ------------------------------------
      # wasmer
      # ------------------------------------
      source /home/gitpod/.wasmer/wasmer.sh
      wasmer --version
      # ------------------------------------
      # wasmtime
      # ------------------------------------
      wasmtime --version
      # ------------------------------------
      # wasmedge dependencies
      # ------------------------------------
      source /home/gitpod/.wasmedge/env
      wasmedge --version

    init: |
      echo "🚀 initialize"
      #npm install
      clear

  - name: wazero-step-by-step
    command: |
      cd wazero-step-by-step
      clear

  - name: wazero-step-by-step/01-wasi-simple-function
    command: |
      cd wazero-step-by-step/01-wasi-simple-function
      clear

  - name: wazero-step-by-step/02-wasi-host-function
    command: |
      cd wazero-step-by-step/02-wasi-host-function
      clear

  - name: zero-to-hero
    command: |
      cd zero-to-hero
      clear

  - name: zero-to-hero/01-use-cli-grain-division
    command: |
      cd zero-to-hero/01-use-cli-grain-division
      clear
      exa --oneline

  - name: zero-to-hero/02-go-sat
    command: |
      cd zero-to-hero/02-go-sat
      clear
      exa --oneline

  - name: zero-to-hero/02-go-sat/bis
    openMode: split-right
    command: |
      cd zero-to-hero/02-go-sat
      clear

  - name: zero-to-hero/03-sat/as-service
    command: |
      cd zero-to-hero/03-sat
      clear
      exa --oneline

  - name: zero-to-hero/03-sat/js-service
    openMode: split-right
    command: |
      cd zero-to-hero/03-sat
      clear
      exa --oneline

  - name: zero-to-hero/03-sat/hello-service
    command: |
      cd zero-to-hero/03-sat
      clear
      exa --oneline

  - name: zero-to-hero/03-sat/query-service
    openMode: split-right
    command: |
      cd zero-to-hero/03-sat
      clear
      exa --oneline

ports:
  - port: 8080
    visibility: public
  - port: 3000
    visibility: public
  - port: 5000
    visibility: public

vscode:
  extensions:
    - golang.go
    - pkief.material-icon-theme
    - aaron-bond.better-comments
